version: '3.8'
services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    environment:
      NODE_ENV: "production"
    depends_on:
      - database
    networks:
      - app_network

  database:
    image: postgres:alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/redis/data
    ports:
      - "6379:6379"

volumes:
  pg_data:
  redis_data:

networks:
  app_network:
    driver: bridge